# Generated by Django 4.1.7 on 2023-04-18 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0005_musician_album'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='album',
            name='num_stars',
        ),
        migrations.AddField(
            model_name='album',
            name='monthly_income',
            field=models.BigIntegerField(default=1000),
        ),
    ]
