# Generated by Django 4.1.7 on 2023-04-18 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0006_remove_album_num_stars_album_monthly_income'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='published',
            field=models.BooleanField(default=True),
        ),
    ]
