# Generated by Django 4.1.7 on 2023-04-18 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0007_album_published'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='published_time',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
