# Generated by Django 4.1.7 on 2023-04-18 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0008_album_published_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='monthly_income',
            field=models.BigIntegerField(blank=True, default=1000, help_text='arbitrariness'),
        ),
    ]
