# Generated by Django 4.1.7 on 2023-04-18 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0009_alter_album_monthly_income'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='Email',
            field=models.EmailField(help_text='Enter the Musician Email', max_length=254, null=True),
        ),
    ]
