# Generated by Django 4.1.7 on 2023-04-19 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('age', models.PositiveIntegerField(blank=True, null=True)),
                ('alias', models.CharField(blank=True, max_length=100, null=True)),
                ('goes_by', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
    ]
