# Generated by Django 4.1.7 on 2023-04-25 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accessory', '0003_accessory_count_accessory_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accessory',
            name='count',
            field=models.IntegerField(default=1),
        ),
    ]
