# Generated by Django 4.1.7 on 2023-04-09 17:53

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('magazine', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='example',
            name='last_modified',
        ),
        migrations.AddField(
            model_name='example',
            name='publish_date',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='example',
            name='title',
            field=models.CharField(max_length=40),
        ),
    ]
