# Generated by Django 4.1.7 on 2023-04-11 08:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('magazine', '0004_newmodel_delete_geeksmodel'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='newModel',
            new_name='MagazineModel',
        ),
    ]
